language: node_js

node_js:
    - "node"
    - "14"
    - "12"
    - "10"
    - "8"

sudo: false

git:
    submodules: false

addons:
    firefox: "60.0.1"

before_install:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver

install:
    - npm install selenium-webdriver@^3.0.0
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
