language: node_js

node_js:
    - "node"
    - "14"
    - "12"
    - "10"
    - "8"

sudo: false

git:
    submodules: false

addons:
    firefox: "49.0.2"

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
